# Generated by Django 3.2.11 on 2022-04-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersdata', '0002_auto_20220408_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_address_street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_address_zip',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
