# Generated by Django 3.2.11 on 2022-04-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersdata', '0003_auto_20220409_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_address_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
