# Generated by Django 3.2.11 on 2022-04-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersdata', '0005_auto_20220409_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
