# Generated by Django 3.2.11 on 2022-04-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersdata', '0006_alter_member_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_Volunteer_Interests',
        ),
        migrations.AddField(
            model_name='member',
            name='member_volunteer_interests',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Volunteer Interests'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_DL',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DL'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_address_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_address_state',
            field=models.CharField(blank=True, choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=14, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_address_street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_address_zip',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='ZIP Code'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_cell_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Cell Phone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_child1_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Child 1 Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_child2_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Child 2 Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_child3_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Child 3 Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_child4_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Child 4 Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_child5_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Child 5 Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_child6_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Child 6 Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_child7_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Child 7 Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_child8_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Child 8 Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_duespaid',
            field=models.DateField(blank=True, null=True, verbose_name='Dues Paid Date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_fax',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='FAX Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_last_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Home Phone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_secondary_first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary First Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Member Type'),
        ),
    ]
