# Generated by Django 3.2.11 on 2022-04-13 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membersdata', '0007_auto_20220413_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_last_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_secondary_first_name',
        ),
    ]
