# Generated by Django 3.2.11 on 2022-04-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersdata', '0008_auto_20220413_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_last_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_secondary_first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary First Name'),
        ),
    ]
