# Generated by Django 3.2.11 on 2022-04-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersdata', '0009_auto_20220413_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_identification', models.CharField(blank=True, max_length=1, null=True, verbose_name='Spot ID')),
                ('spot_res_status', models.CharField(default='A', max_length=1, verbose_name='Spot Reserve Satus')),
            ],
        ),
    ]
