# Generated by Django 3.2.11 on 2022-04-15 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membersdata', '0010_spot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spot',
        ),
    ]
